### ISSUE TITLE
Incorrect login details were provided

### ISSUE THREAD

**Issue by OFFchase** [Hoi15A/simple-discord-bot#41]
(node:8660) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\aminy\Documents\GitHub\bot\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:421:26)
    at WebSocketConnection.emit (events.js:314:20)
    at WebSocketConnection.onClose (C:\Users\aminy\Documents\GitHub\bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:393:10)
    at WebSocket.onClose (C:\Users\aminy\Documents\GitHub\bot\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (C:\Users\aminy\Documents\GitHub\bot\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\aminy\Documents\GitHub\bot\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:326:22)
    at net.js:673:12

**Comment by Hoi15A** [comment]
Are you sure you provided a valid token inside the .env file? This error should not be thrown if the credentials are valid. See the [Readme](https://github.com/Hoi15A/simple-discord-bot#configuration) for how the .env file is supposed to be structured.

Also I dont know if you have noticed but I dont super actively maintain this repo and the bot will definitely stop working around october/november if I dont update it to djs v12 by then

**Comment by Hoi15A** [comment]
Closed for inactivity
